Sys.setenv("LANGUAGE"="En")
Sys.setlocale("LC_ALL","English")
library(sqldf)
setwd("data scientist track/exploratory data analysis")
power_date <- read.csv.sql("household_power_consumption.txt", header = TRUE, sep = ";", 
                             sql = "select Global_active_power, Date, Time from file where Date = '1/2/2007' or Date = '2/2/2007'")
datetime <- strptime(paste(power_date$Date, power_date$Time, sep=" "), format = "%d/%m/%Y %H:%M:%S", tz="UTC")
png(filename = "plot2.png",width = 480, height = 480)
plot(x=datetime, y=power_date$Global_active_power, type="l",xlab = "", ylab = "Global Active Power (kilowalts)")
dev.off()